package org.example.view;

import javax.swing.JOptionPane;

import org.example.controllers.RegisterController;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author daxxe
 */
public class RegisterView extends javax.swing.JFrame {
    private RegisterController controller;

    private String[] careers = new String[] {
            "Selecciona una carrera", "Ing. Sistemas Computacionales",
            "Ing. Industrial", "Ing. Macarrónica", "Ing. Empresas"
    };

    private String[] semesters = new String[] {
            "Selecciona un semestre",
            "1", "2", "3", "4", "5",
            "6", "7", "8", "9", "10",
            "11", "12", "13", "14", "15"
    };

    /**
     * Creates new form Form
     */
    public RegisterView() {
        initComponents();
        setVisible(true);

        controller = new RegisterController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        mothersLastNameLabel = new javax.swing.JLabel();
        fathersLastNameLabel = new javax.swing.JLabel();
        controlNumberLabel = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        careerLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        controlNumberInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        fathersLastNameInput = new javax.swing.JTextField();
        careerComboBox = new javax.swing.JComboBox<>();
        semesterComboBox = new javax.swing.JComboBox<>();
        mothersLastNameInput = new javax.swing.JTextField();
        subtitleLabel = new javax.swing.JLabel();
        addStudentButton = new javax.swing.JButton();
        watchListButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        nameLabel.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        nameLabel.setText("Nombre");

        mothersLastNameLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        mothersLastNameLabel.setText("Apellido 2");

        fathersLastNameLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        fathersLastNameLabel.setText("Apellido 1");

        controlNumberLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        controlNumberLabel.setText("Número de Control");

        semesterLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        semesterLabel.setText("Semestre");

        careerLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        careerLabel.setText("Carrera");

        emailLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        emailLabel.setText("Correo");

        nameInput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        controlNumberInput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        emailInput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fathersLastNameInput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        careerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(careers));
        careerComboBox.setToolTipText(careers[0]);

        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(semesters));
        careerComboBox.setToolTipText(semesters[0]);

        mothersLastNameInput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        subtitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtitleLabel.setText("Responde cuidadosamente el siguiente formulario");

        addStudentButton.setBackground(new java.awt.Color(0, 51, 51));
        addStudentButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        addStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        addStudentButton.setText("Agregar");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        watchListButton.setBackground(new java.awt.Color(0, 51, 51));
        watchListButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        watchListButton.setForeground(new java.awt.Color(255, 255, 255));
        watchListButton.setText("Cerrar");
        watchListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerLista1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(mothersLastNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(controlNumberLabel)
                                                .addGap(251, 251, 251))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addComponent(careerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(87, 87, 87))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(careerLabel)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        362, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(mothersLastNameInput)
                                                                .addGap(157, 157, 157)))
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(controlNumberInput,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 255,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(semesterLabel))
                                                .addGap(117, 117, 117))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(nameInput,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                255,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(nameLabel))
                                                                .addGap(157, 157, 157)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(fathersLastNameLabel)
                                                                        .addComponent(fathersLastNameInput,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                255,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(emailLabel)
                                                        .addComponent(subtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(emailInput,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 255,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(181, 181, 181)
                                                                .addComponent(addStudentButton)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(watchListButton)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(subtitleLabel)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameLabel)
                                        .addComponent(fathersLastNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fathersLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mothersLastNameLabel)
                                        .addComponent(controlNumberLabel))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(controlNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mothersLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(careerLabel)
                                        .addComponent(semesterLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(careerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(emailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(watchListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(70, Short.MAX_VALUE)));

        titleLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        titleLabel.setText("Registro de Estudiantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(36, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleLabel)
                                .addGap(291, 291, 291)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(titleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VerListaActionPerformed
        String name = nameInput.getText();
        String fathersLastName = fathersLastNameInput.getText();
        String mothersLastName = mothersLastNameInput.getText();
        String email = emailInput.getText();
        String id = controlNumberInput.getText();
        String semester = (String) semesterComboBox.getSelectedItem();
        String career = (String) careerComboBox.getSelectedItem();

        if (name.isEmpty() || fathersLastName.isEmpty() || email.isEmpty() || id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Rellene todos los datos");
            return;
        }

        if (career == careers[0] || semester == semesters[0]) {
            JOptionPane.showMessageDialog(null, "Por favor selecciona un campo válido");
            return;
        }

        try {
            Integer.parseInt(id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un valor válido");
            return;
        }

        if(email.matches("\"^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$\"")) {
            JOptionPane.showMessageDialog(null, "Email no válido");
            return;
        }

        if (mothersLastName.isEmpty()) {
            boolean savedSuccess = controller.registerStudent(id, name, fathersLastName, email, semester, career);

            if (savedSuccess == false) {
                JOptionPane.showMessageDialog(null,
                        "De momento, no podemos guardar tu información. Por favor, intenta más tarde");
                return;
            }

            JOptionPane.showMessageDialog(null,
                    "Estudiante guardado");
            return;
        }

        boolean savedSuccess = controller.registerStudent(id, name, fathersLastName, mothersLastName, email, semester,
                career);

        if (savedSuccess == false) {
            JOptionPane.showMessageDialog(null,
                    "De momento, no podemos guardar tu información. Por favor, intenta más tarde");

            return;
        }

        JOptionPane.showMessageDialog(null,
                "Estudiante guardado");
    }// GEN-LAST:event_VerListaActionPerformed

    private void VerLista1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VerLista1ActionPerformed
        System.exit(0);
    }// GEN-LAST:event_VerLista1ActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_inputNombreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> careerComboBox;
    private javax.swing.JLabel controlNumberLabel;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton watchListButton;
    private javax.swing.JTextField fathersLastNameInput;
    private javax.swing.JTextField mothersLastNameInput;
    private javax.swing.JTextField emailInput;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField controlNumberInput;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel fathersLastNameLabel;
    private javax.swing.JLabel mothersLastNameLabel;
    private javax.swing.JLabel careerLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel semesterLabel;
    // End of variables declaration//GEN-END:variables
}